---
id: Lens
name: Lens
full: Lens decorating iterator/flyweight library
description: >-
  A library for wrapping iterators to avoid looping over them multiple times,
  using a single decorator object (the "lens") instead of creating one decorator
  for every element.
list: dev
type: library
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 1.0.0alpha2
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
